### ISSUE TITLE
Dev notes for master branch.

### ISSUE THREAD

**Issue by futhr** [spree-contrib/spree_related_products#101]
After some refactor on `master` branch I noticed some things that can be improved or need to be fixed:

- [ ] Need to look into issue #82 and add better specs for the calculator that proper test discounts.
- [ ] The delete related record need to be rebuilt, it doesn't work and the JS inject the list after delete totally wrong. This is related to issue #95
- [ ] Need to look into issue #88 concerning `has_related_products?`

_These are dev memory notes, you welcome to help out with PR._
